openapi: "3.0.0"
info:
  version: 1.0.0
  title: MediaControllerAPI
  description: API for uploading and processing image and video files.

paths:
  /api/upload-image:
    post:
      summary: Uploads an image file for processing.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
              required:
                - image
      responses:
        '200':
          description: Returns the processed image.
          content:
            image/png:
              schema:
                type: string
                format: binary
        '400':
          description: No image file provided.

  /api/upload-video:
    post:
      summary: Uploads a video file for processing.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                video:
                  type: string
                  format: binary
              required:
                - video
      responses:
        '200':
          description: Returns the processed video.
          content:
            video/webm:
              schema:
                type: string
                format: binary
        '400':
          description: No video file provided.